### ISSUE TITLE
KeyError in Markov Chain Encoder

### ISSUE THREAD

**Issue by Gidsss** [Gidsss/DMSDjango#4]
# Error:
`Traceback (most recent call last):
  File "C:\Python 3.12\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Python 3.12\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python 3.12\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Python Projects\fms_django\fmsApp\views.py", line 223, in save_post
    encoder.generate()
  File "fmsApp\\stegomarkov.pyx", line 114, in fmsApp.stegomarkov.Encoder.generate
    self.step()
  File "fmsApp\\stegomarkov.pyx", line 79, in fmsApp.stegomarkov.Encoder.step
    self._choose_next_token()
  File "fmsApp\\stegomarkov.pyx", line 92, in fmsApp.stegomarkov.Encoder._choose_next_token
    transitions = self._get_transitions(self.current_gram)
  File "fmsApp\\stegomarkov.pyx", line 132, in fmsApp.stegomarkov.Encoder._get_transitions
    trans_matrix = self.model.chain.model[gram]
KeyError: ('just',)`

## Steps to Reproduce:

1. Perform the action that triggers the save_post view (e.g., submitting a post).
2. The error occurs in the Encoder.generate() function during token selection (_choose_next_token).

Expected Behavior: The model should select a valid transition without raising a KeyError.
Actual Behavior: A KeyError is raised because the key ('just',) does not exist in the transition matrix.

## Potential Cause:
The key ('just',) might not exist in the trained model, suggesting a possible issue with the training data or the Markov chain's transitions.
The Markov chain model might be incomplete, or the current state (self.current_gram) is not handled correctly when it doesn't exist in the model.

**Comment by Gidsss** [comment]
solved
